- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.install_conf_dir }}'

- name: Copy install-config.yaml to the {{ helper.install_conf_dir }} directory
  template:
    src: files/common/install-config.yaml
    dest: '{{ helper.install_conf_dir }}'

- name: Create a backup copy of install-config.yaml as the installer deletes the original
  template:
    src: files/common/install-config.yaml
    dest: '{{ helper.install_conf_dir }}/install-config.backup.yaml'
    backup: True

- name: Create Kubernetes manifests # noqa 301
  command: |
    {{ helper.install_exe }} create manifests --dir '{{ helper.install_conf_dir }}'

- name : Mark control plane as unscheduleable
  lineinfile:
    path: '{{ openshift_install_dir }}/manifests/cluster-scheduler-02-config.yml'
    regexp: '^(\s*mastersSchedulable:)'
    line: '\1 false'
    backrefs: True

- name: Create ignition configs # noqa 301
  command: |
    {{ helper.install_exe }} create ignition-configs --dir '{{ helper.install_conf_dir }}'
